# Generated by Django 5.2.8 on 2025-11-21 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='commission_percentage',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='commission_earned',
        ),
    ]
