# Generated by Django 5.2.8 on 2025-11-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_product_sale_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Verified', 'Verified'), ('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Won', 'Won'), ('Lost', 'Lost')], default='New', max_length=20),
        ),
    ]
