# Generated by Django 5.2.8 on 2025-11-21 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_lead_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='lead',
            name='document_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Submitted', 'Submitted'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='employment_type',
            field=models.CharField(choices=[('Salaried', 'Salaried'), ('Self-employed', 'Self-employed')], default='Salaried', max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='loan_type',
            field=models.CharField(choices=[('Personal', 'Personal Loan'), ('Home', 'Home Loan'), ('Car', 'Car Loan'), ('Education', 'Education Loan'), ('Business', 'Business Loan')], default='Personal', max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='eligibility_criteria',
            field=models.TextField(blank=True, help_text='Eligibility rules'),
        ),
        migrations.AddField(
            model_name='product',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Interest Rate %', max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='max_amount',
            field=models.DecimalField(decimal_places=2, default=1000000, max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='processing_fee',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Processing Fee %', max_digits=5),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Follow-up', 'Follow-up'), ('Verified', 'Verified'), ('Converted', 'Converted'), ('Rejected', 'Rejected')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='value',
            field=models.DecimalField(decimal_places=2, help_text='Loan Amount Required', max_digits=12),
        ),
        migrations.AlterField(
            model_name='sale',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.CreateModel(
            name='LeadDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., ID Proof, Income Proof', max_length=100)),
                ('file', models.FileField(upload_to='lead_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Submitted', 'Submitted'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Submitted', max_length=20)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.lead')),
            ],
        ),
    ]
