# Generated by Django 5.2.8 on 2025-11-21 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_remove_product_price_lead_document_status_lead_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='product',
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='LoanProduct',
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Applicant Name')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('loan_type', models.CharField(choices=[('Personal', 'Personal Loan'), ('Home', 'Home Loan'), ('Car', 'Car Loan'), ('Education', 'Education Loan'), ('Business', 'Business Loan')], default='Personal', max_length=50)),
                ('employment_type', models.CharField(choices=[('Salaried', 'Salaried'), ('Self-employed', 'Self-employed')], default='Salaried', max_length=50)),
                ('status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Follow-up', 'Follow-up'), ('Verified', 'Verified'), ('Converted', 'Converted'), ('Rejected', 'Rejected')], default='New', max_length=20)),
                ('document_status', models.CharField(choices=[('Pending', 'Pending'), ('Submitted', 'Submitted'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Loan Amount Required', max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='crm.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('banker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='crm.employee')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.loanproduct')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disbursement', to='crm.loanapplication')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., ID Proof, Income Proof', max_length=100)),
                ('file', models.FileField(upload_to='application_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Submitted', 'Submitted'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Submitted', max_length=20)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.loanapplication')),
            ],
        ),
        migrations.DeleteModel(
            name='LeadDocument',
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
