# Generated by Django 5.2.8 on 2025-11-22 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_remove_lead_assigned_to_remove_sale_lead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Loan Officer', 'Loan Officer'), ('Sales Executive', 'Sales Executive'), ('Bank Teller', 'Bank Teller')], default='Loan Officer', max_length=50),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.loanproduct', verbose_name='Loan Type'),
        ),
    ]
