# Generated by Django 5.2.8 on 2025-11-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_employee_designation_alter_loanapplication_loan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanproduct',
            name='name',
            field=models.CharField(choices=[('Personal Loan', 'Personal Loan'), ('Home Loan', 'Home Loan'), ('Car Loan', 'Car Loan'), ('Gold Loan', 'Gold Loan'), ('Education Loan', 'Education Loan'), ('Business Loan', 'Business Loan'), ('Mortgage Loan', 'Mortgage Loan'), ('Credit Card', 'Credit Card')], max_length=200),
        ),
    ]
